# Generated by Django 5.0.8 on 2025-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cls', models.IntegerField()),
                ('roll', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
